FROM dorowu/ubuntu-desktop-lxde-vnc:latest

# Install Python 3.11
RUN wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
RUN apt update \
    && add-apt-repository ppa:deadsnakes/ppa \
    && apt update \
    && apt install -y --no-install-recommends --allow-unauthenticated python3.11 build-essential python3.11-dev python3.11-tk libevdev-dev\
    && apt autoclean -y \
    && apt autoremove -y \
    && rm -rf /var/lib/apt/lists/*

# Download get-pip.py and install pip for Python 3.11
RUN wget https://bootstrap.pypa.io/get-pip.py \
    && python3.11 get-pip.py \
    && python3.11 -m pip install --upgrade pip

COPY . /root/playground
WORKDIR /root/playground
RUN python3.11 -m pip install -e .
RUN python3.11 -m pip install -r requirements_linux.txt
RUN chmod +x /root/playground/scripts/docker_startup.sh
ENTRYPOINT ["/root/playground/scripts/docker_startup.sh"]
